language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
install: true
script:
  - ./mvnw clean install
  - ./mvnw cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)   